stages:
  - dockerize

image: docker
services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

after_script:
  - docker logout $CI_REGISTRY

dockerize_wimute:
  stage: dockerize
  script:
    - 'docker run --rm -v $CI_PROJECT_DIR:/go/src/github.com/keycloak/keycloak-gatekeeper -w /go/src/github.com/keycloak/keycloak-gatekeeper -e GOOS=linux golang:1.10.2 && pwd && ls -l bin/'
    - 'docker build --tag $CI_REGISTRY/$CI_PROJECT_PATH:wimute --tag $CI_REGISTRY/$CI_PROJECT_PATH:latest .'
    - 'docker push $CI_REGISTRY/$CI_PROJECT_PATH:wimute'
    - 'docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest'
  only:
    refs:
      - wimute

